#include <chrono>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
#ifdef CSP_CUDA
#include <cuda_runtime.h>
#endif
#include "src/diagnostic.hpp"
#include "src/ir.hpp"
#include "src/lexer.hpp"
#include "src/lowering.hpp"
#include "src/parser.hpp"
#include "src/semantic.hpp"
#include "src/thir.hpp"
#include "src/tooling.hpp"
#include "src/transpiler.hpp"

namespace fs = std::filesystem;

static const char *VERSION = "0.2.0";

static const char *RUNTIME = R"CSP(
#ifndef CSP_CPSTREAM_DEFINED
#define CSP_CPSTREAM_DEFINED
#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <cstddef>
#include <cstring>
#include <string>
#include <vector>
using u8 = std::uint8_t;
using u16 = std::uint16_t;
using u32 = std::uint32_t;
using u64 = std::uint64_t;
using u128 = unsigned __int128;
using unichar = char32_t;
#ifdef CSP_CUDA
constexpr auto cspHostToDevice = cudaMemcpyHostToDevice;
constexpr auto cspDeviceToHost = cudaMemcpyDeviceToHost;
#endif
template<class... Args> int printc(const char* format, Args... args) {
    return std::printf(format, args...);
}
inline int printc(const std::string& value) {
    return std::printf("%s", value.c_str());
}
#endif
)CSP";

static std::string read_file(const fs::path &path) {
  std::ifstream input(path, std::ios::binary);
  if (!input)
    throw std::runtime_error("cannot open source file: " + path.string());
  return {std::istreambuf_iterator<char>(input),
          std::istreambuf_iterator<char>()};
}

static void write_file(const fs::path &path, const std::string &data) {
  std::ofstream output(path, std::ios::binary);
  if (!output)
    throw std::runtime_error("cannot write file: " + path.string());
  output << data;
}

static std::string transpile(std::string source, const fs::path &filename,
                             bool include_runtime) {
  std::string display = filename.generic_string();
  return "// Generated by C+ " + std::string(VERSION) + "\n" +
         "#include <optional>\n" +
         (include_runtime ? std::string(RUNTIME) : std::string()) +
         "\n#line 1 \"" + display + "\"\n" + source + "\n";
}

static std::string quote(const fs::path &value) {
  std::string text = value.string();
  std::string escaped = "\"";
  for (char c : text)
    escaped += (c == '"' ? "\\\"" : std::string(1, c));
  return escaped + "\"";
}

static void usage() {
  std::cout
      << "C+ native compiler " << VERSION << "\n"
      << "Usage: cspc [command] <source.csp> [options]\n\n"
      << "Commands:\n"
      << "  build run hopa check fmt lint reflect lex parse stats thir hir mir "
         "lower cpp c rust llvm asm object\n"
      << "  cuda debug release fast safe sanitize warnings freestanding\n"
      << "  targets features doctor env commands version help\n\n"
      << "Options: [-o program.exe] [--emit-cpp file.cpp]\n"
      << "             [--compiler g++] [--cuda] [--gpu-arch sm_86]\n"
      << "             [--emit-llvm | -S | -c] [--target triple] [--cpu cpu]\n"
      << "             [--emit-c | --emit-rust]\n"
      << "             [--native] [--lto] [--fast-math]\n"
      << "             [--thin-lto] [--vectorize | --no-vectorize]\n"
      << "             [--check] [--recover] [--ast-json file]\n"
      << "             [--freestanding | --no-runtime]\n"
      << "             [-I path] [-D name] [-O level] [-g] [--run]\n";
}

static bool tool_available(const char *name) {
#ifdef _WIN32
  return std::system((std::string("where ") + name + " >NUL 2>&1").c_str()) ==
         0;
#else
  return std::system((std::string("command -v ") + name + " >/dev/null 2>&1")
                         .c_str()) == 0;
#endif
}

static bool informational_command(const std::string &command) {
  if (command == "targets") {
    std::cout << "native\nx86_64\naarch64\nriscv64\nwasm32\nnvptx64 (CUDA)\n";
  } else if (command == "features") {
    std::cout
        << "THIR type inference\nHIR and verified CFG MIR\n"
           "C++20 backend\nC/Rust transpilers\nLLVM IR\nassembly/object "
           "emission\n"
           "CUDA mode\nfreestanding mode\nsemantic analysis\nrecovery parser\n"
           "AST JSON\nCTFE\nexhaustive match\nC ABI\nLTO/vectorization\n"
           "sanitisers\nsafety hardening\n";
  } else if (command == "commands") {
    usage();
  } else if (command == "doctor") {
    const char *tools[] = {"g++", "clang++", "rustc", "nvcc", "go"};
    for (const char *tool : tools)
      std::cout << (tool_available(tool) ? "ok       " : "missing  ") << tool
                << '\n';
  } else if (command == "env") {
    const char *names[] = {"CXX", "CC", "CSX_REGISTRY", "CSX_SOURCE_ROOT",
                           "NO_COLOR"};
    for (const char *name : names) {
      const char *value = std::getenv(name);
      std::cout << name << '=' << (value ? value : "") << '\n';
    }
  } else if (command == "version") {
    std::cout << "C+ " << VERSION << "\n";
  } else if (command == "help") {
    usage();
  } else {
    return false;
  }
  return true;
}

static fs::path discover_source() {
  for (const fs::path &candidate :
       {fs::path("main.csp"), fs::path("src/main.csp")})
    if (fs::is_regular_file(candidate))
      return candidate;
  std::vector<fs::path> sources;
  for (const auto &entry : fs::directory_iterator(fs::current_path()))
    if (entry.is_regular_file() && entry.path().extension() == ".csp")
      sources.push_back(entry.path());
  return sources.size() == 1 ? sources.front() : fs::path{};
}

int main(int argc, char **argv) {
  try {
    if (argc == 1) {
      usage();
      return 1;
    }
    fs::path source, output, emit_cpp, ast_json, emit_thir, emit_hir, emit_mir;
    enum class OutputMode {
      Executable,
      Object,
      Assembly,
      LlvmIr,
      SyntaxOnly,
      Formatter,
      Lint,
      Reflection,
      Thir,
      Hir,
      Mir,
      LoweredSource,
      CppSource,
      CSource,
      RustSource
    };
    OutputMode output_mode = OutputMode::Executable;
    std::string compiler, gpu_arch, target_triple, target_cpu;
    std::vector<std::string> native_flags;
    bool run = false, dump_tokens = false, dump_ast = false, cuda = false,
         recover = false, freestanding = false, no_runtime = false,
         print_stats = false, command_ast_json = false, hopa = false,
         format_check = false, format_stdout = false;

    int first_argument = 1;
    const std::string cli_command = argv[1];
    if (informational_command(cli_command))
      return 0;
    const std::vector<std::string> compiler_commands = {
        "build", "run",      "hopa",     "check",        "fmt",
        "lint",  "reflect",  "lex",      "parse",        "stats",
        "thir",  "hir",      "mir",      "lower",        "cpp",
        "c",     "rust",     "llvm",     "asm",          "object",
        "cuda",  "debug",    "release",  "fast",         "vectorized",
        "safe",  "sanitize", "warnings", "freestanding", "ast-json"};
    bool has_command = false;
    for (const auto &known : compiler_commands)
      if (cli_command == known) {
        has_command = true;
        break;
      }
    if (has_command) {
      first_argument = 2;
      if (cli_command == "run")
        run = true;
      else if (cli_command == "hopa")
        hopa = true;
      else if (cli_command == "check")
        output_mode = OutputMode::SyntaxOnly;
      else if (cli_command == "fmt")
        output_mode = OutputMode::Formatter;
      else if (cli_command == "lint")
        output_mode = OutputMode::Lint;
      else if (cli_command == "reflect")
        output_mode = OutputMode::Reflection;
      else if (cli_command == "lex") {
        dump_tokens = true;
        output_mode = OutputMode::SyntaxOnly;
      } else if (cli_command == "parse") {
        dump_ast = true;
        output_mode = OutputMode::SyntaxOnly;
      } else if (cli_command == "stats") {
        print_stats = true;
        output_mode = OutputMode::SyntaxOnly;
      } else if (cli_command == "thir")
        output_mode = OutputMode::Thir;
      else if (cli_command == "hir")
        output_mode = OutputMode::Hir;
      else if (cli_command == "mir")
        output_mode = OutputMode::Mir;
      else if (cli_command == "lower")
        output_mode = OutputMode::LoweredSource;
      else if (cli_command == "cpp")
        output_mode = OutputMode::CppSource;
      else if (cli_command == "c")
        output_mode = OutputMode::CSource;
      else if (cli_command == "rust")
        output_mode = OutputMode::RustSource;
      else if (cli_command == "llvm")
        output_mode = OutputMode::LlvmIr;
      else if (cli_command == "asm")
        output_mode = OutputMode::Assembly;
      else if (cli_command == "object")
        output_mode = OutputMode::Object;
      else if (cli_command == "cuda")
        cuda = true;
      else if (cli_command == "debug")
        native_flags.insert(native_flags.end(), {"-O0", "-g"});
      else if (cli_command == "release")
        native_flags.push_back("-O2");
      else if (cli_command == "fast")
        native_flags.insert(native_flags.end(),
                            {"-O3", "-march=native", "-flto"});
      else if (cli_command == "vectorized")
        native_flags.insert(native_flags.end(),
                            {"-O3", "-ftree-vectorize", "-funroll-loops"});
      else if (cli_command == "safe")
        native_flags.insert(
            native_flags.end(),
            {"-O2", "-fstack-protector-strong", "-D_FORTIFY_SOURCE=2"});
      else if (cli_command == "sanitize")
        native_flags.insert(native_flags.end(),
                            {"-O1", "-g", "-fsanitize=address,undefined"});
      else if (cli_command == "warnings")
        native_flags.insert(native_flags.end(),
                            {"-Wall", "-Wextra", "-Wpedantic", "-Wconversion"});
      else if (cli_command == "freestanding") {
        freestanding = true;
        no_runtime = true;
      } else if (cli_command == "ast-json")
        command_ast_json = true;
    }

    for (int i = first_argument; i < argc; ++i) {
      std::string arg = argv[i];
      auto value = [&](const char *option) -> std::string {
        if (++i >= argc)
          throw std::runtime_error(std::string("missing value for ") + option);
        return argv[i];
      };
      if (arg == "-o" || arg == "--output")
        output = value(arg.c_str());
      else if (arg == "--emit-cpp")
        emit_cpp = value("--emit-cpp");
      else if (arg == "--ast-json")
        ast_json = value("--ast-json");
      else if (arg == "--emit-hir")
        emit_hir = value("--emit-hir");
      else if (arg == "--emit-thir")
        emit_thir = value("--emit-thir");
      else if (arg == "--emit-mir")
        emit_mir = value("--emit-mir");
      else if (arg == "--compiler")
        compiler = value("--compiler");
      else if (arg == "--cuda")
        cuda = true;
      else if (arg == "--gpu-arch")
        gpu_arch = value("--gpu-arch");
      else if (arg == "--emit-llvm")
        output_mode = OutputMode::LlvmIr;
      else if (arg == "--emit-c")
        output_mode = OutputMode::CSource;
      else if (arg == "--emit-rust")
        output_mode = OutputMode::RustSource;
      else if (arg == "--check") {
        if (output_mode == OutputMode::Formatter)
          format_check = true;
        else
          output_mode = OutputMode::SyntaxOnly;
      } else if (arg == "--stdout")
        format_stdout = true;
      else if (arg == "--recover")
        recover = true;
      else if (arg == "--freestanding") {
        freestanding = true;
        no_runtime = true;
      } else if (arg == "--no-runtime")
        no_runtime = true;
      else if (arg == "-S")
        output_mode = OutputMode::Assembly;
      else if (arg == "-c")
        output_mode = OutputMode::Object;
      else if (arg == "--target")
        target_triple = value("--target");
      else if (arg == "--cpu")
        target_cpu = value("--cpu");
      else if (arg == "--native")
        native_flags.push_back("-march=native");
      else if (arg == "--lto")
        native_flags.push_back("-flto");
      else if (arg == "--thin-lto")
        native_flags.push_back("-flto=thin");
      else if (arg == "--vectorize")
        native_flags.push_back("-ftree-vectorize");
      else if (arg == "--no-vectorize")
        native_flags.push_back("-fno-tree-vectorize");
      else if (arg == "--fast-math")
        native_flags.push_back("-ffast-math");
      else if (arg == "-I" || arg == "-D" || arg == "-L" || arg == "-l" ||
               arg == "-O")
        native_flags.push_back(arg + value(arg.c_str()));
      else if (arg.rfind("-I", 0) == 0 || arg.rfind("-D", 0) == 0 ||
               arg.rfind("-L", 0) == 0 || arg.rfind("-l", 0) == 0 ||
               arg.rfind("-O", 0) == 0 || arg == "-g")
        native_flags.push_back(arg);
      else if (arg == "--run")
        run = true;
      else if (arg == "--dump-tokens")
        dump_tokens = true;
      else if (arg == "--dump-ast")
        dump_ast = true;
      else if (arg == "--version") {
        std::cout << "C+ " << VERSION << "\n";
        return 0;
      } else if (arg == "-h" || arg == "--help") {
        usage();
        return 0;
      } else if (!arg.empty() && arg[0] == '-')
        throw std::runtime_error("unknown option: " + arg);
      else if (source.empty())
        source = arg;
      else
        throw std::runtime_error(
            "only one source file may be compiled at a time");
    }

    if (source.empty())
      source = discover_source();
    if (source.empty())
      throw std::runtime_error("a .csp source file is required (or create "
                               "main.csp for automatic discovery)");
    if (source.extension() != ".csp")
      throw std::runtime_error("source files must use .csp");
    if (output.empty()) {
      output = source;
      if (output_mode == OutputMode::LlvmIr)
        output.replace_extension(".ll");
      else if (output_mode == OutputMode::Thir)
        output.replace_extension(".thir");
      else if (output_mode == OutputMode::Hir)
        output.replace_extension(".hir");
      else if (output_mode == OutputMode::Mir)
        output.replace_extension(".mir");
      else if (output_mode == OutputMode::Reflection)
        output.replace_extension(".reflection.json");
      else if (output_mode == OutputMode::LoweredSource)
        output.replace_extension(".lowered.cpp");
      else if (output_mode == OutputMode::CppSource)
        output.replace_extension(".cpp");
      else if (output_mode == OutputMode::CSource)
        output.replace_extension(".c");
      else if (output_mode == OutputMode::RustSource)
        output.replace_extension(".rs");
      else if (output_mode == OutputMode::Assembly)
        output.replace_extension(".s");
      else if (output_mode == OutputMode::Object)
        output.replace_extension(".o");
      else if (hopa) {
        output.replace_filename(output.stem().string() + "-stage1.exe");
      } else
        output.replace_extension(".exe");
    }
    if (command_ast_json && ast_json.empty()) {
      ast_json = source;
      ast_json.replace_extension(".ast.json");
      output_mode = OutputMode::SyntaxOnly;
    }

    std::string source_text = read_file(source);
    if (output_mode == OutputMode::Formatter) {
      const std::string formatted = csp::format_source(source_text);
      if (format_check) {
        if (formatted != source_text) {
          std::cerr << source.string() << ": formatting differs\n";
          return 1;
        }
        std::cout << source.string() << ": formatting is clean\n";
        return 0;
      }
      if (format_stdout)
        std::cout << formatted;
      else {
        write_file(source, formatted);
        std::cout << "Formatted " << source.string() << "\n";
      }
      return 0;
    }
    csp::Lexer lexer(source_text, source.string());
    auto tokens = lexer.tokenize();
    if (output_mode == OutputMode::Lint) {
      const auto issues =
          csp::lint_source(source_text, tokens, source.string());
      for (const auto &issue : issues)
        std::cout << issue.location.file << ':' << issue.location.line << ':'
                  << issue.location.column << ": "
                  << (issue.error ? "error" : "warning") << '[' << issue.rule
                  << "]: " << issue.message << '\n';
      std::cout << issues.size() << " lint issue(s)\n";
      return issues.empty() ? 0 : 1;
    }
    if (dump_tokens)
      for (const auto &token : tokens)
        std::cout << token.location.line << ':' << token.location.column << ' '
                  << csp::token_name(token.kind) << "  " << token.text << '\n';
    std::unique_ptr<csp::Node> ast;
    try {
      csp::Parser parser(tokens);
      csp::DiagnosticEngine diagnostics;
      ast = recover ? parser.parse_recovering(diagnostics) : parser.parse();
      csp::SemanticAnalyzer semantics(diagnostics);
      if (!diagnostics.has_errors())
        semantics.analyze(*ast);
      if (diagnostics.has_errors()) {
        diagnostics.print(std::cerr);
        throw std::runtime_error("semantic analysis failed");
      }
      if (diagnostics.warning_count())
        diagnostics.print(std::cerr);
      if (dump_ast)
        ast->dump(std::cout);
      if (!ast_json.empty()) {
        std::ofstream json(ast_json);
        if (!json)
          throw std::runtime_error("cannot write AST JSON: " +
                                   ast_json.string());
        csp::write_json(*ast, json);
        json << '\n';
      }
      if (print_stats)
        std::cout << "bytes " << source_text.size() << "\ntokens "
                  << (tokens.empty() ? 0 : tokens.size() - 1) << "\n";
    } catch (const csp::CompileError &) {
      // The C+ parser owns C+ extensions. The native backend remains the
      // authority for the much larger C++/CUDA grammar during migration.
      if (dump_ast || dump_tokens)
        throw;
    }

    if (!ast &&
        (output_mode == OutputMode::Thir || output_mode == OutputMode::Hir ||
         output_mode == OutputMode::Mir || !emit_thir.empty() ||
         !emit_hir.empty() || !emit_mir.empty()))
      throw std::runtime_error(
          "THIR/HIR/MIR emission requires a complete C+ AST");
    if (output_mode == OutputMode::Reflection) {
      if (!ast)
        throw std::runtime_error("reflection requires a complete C+ AST");
      write_file(output, csp::reflection_json(*ast, source.generic_string()));
      std::cout << "Emitted reflection metadata " << output.string() << "\n";
      return 0;
    }

    std::optional<csp::HIRModule> hir_module;
    std::optional<csp::MIRModule> mir_module;
    if (ast) {
      csp::THIRBuilder thir_builder;
      auto thir_module = thir_builder.build(*ast, source.generic_string());
      if (!emit_thir.empty()) {
        std::ofstream stream(emit_thir);
        if (!stream)
          throw std::runtime_error("cannot write THIR: " + emit_thir.string());
        thir_module.print(stream);
      }
      if (output_mode == OutputMode::Thir) {
        std::ofstream stream(output);
        if (!stream)
          throw std::runtime_error("cannot write THIR: " + output.string());
        thir_module.print(stream);
        std::cout << "Emitted THIR " << output.string() << "\n";
        return 0;
      }
      csp::HIRBuilder hir_builder;
      hir_module = hir_builder.build(thir_module);
      csp::MIRBuilder mir_builder;
      mir_module = mir_builder.build(*hir_module);
      std::string verification_error;
      if (!mir_module->verify(verification_error))
        throw std::runtime_error("internal MIR verification failed: " +
                                 verification_error);
      if (!emit_hir.empty()) {
        std::ofstream stream(emit_hir);
        if (!stream)
          throw std::runtime_error("cannot write HIR: " + emit_hir.string());
        hir_module->print(stream);
      }
      if (output_mode == OutputMode::Hir) {
        std::ofstream stream(output);
        if (!stream)
          throw std::runtime_error("cannot write HIR: " + output.string());
        hir_module->print(stream);
        std::cout << "Emitted HIR " << output.string() << "\n";
        return 0;
      }
      if (!emit_mir.empty()) {
        std::ofstream stream(emit_mir);
        if (!stream)
          throw std::runtime_error("cannot write MIR: " + emit_mir.string());
        mir_module->print(stream);
      }
      if (output_mode == OutputMode::Mir) {
        std::ofstream stream(output);
        if (!stream)
          throw std::runtime_error("cannot write MIR: " + output.string());
        mir_module->print(stream);
        std::cout << "Emitted MIR " << output.string() << "\n";
        return 0;
      }
    }

    csp::Lowering lowering(source_text, tokens);
    std::string lowered_source = lowering.run();
    if (output_mode == OutputMode::LoweredSource) {
      write_file(output, lowered_source);
      std::cout << "Lowered " << output.string() << "\n";
      return 0;
    }
    if (output_mode == OutputMode::CSource) {
      csp::Lexer lowered_lexer(lowered_source, source.string());
      auto lowered_tokens = lowered_lexer.tokenize();
      write_file(output,
                 csp::Transpiler::emit_c(lowered_source, lowered_tokens));
      std::cout << "Transpiled " << output.string() << "\n";
      return 0;
    }
    if (output_mode == OutputMode::RustSource) {
      if (!ast)
        throw std::runtime_error(
            "Rust transpilation requires a complete C+ AST");
      write_file(output, csp::Transpiler::emit_rust(*ast));
      std::cout << "Transpiled " << output.string() << "\n";
      return 0;
    }
    std::string generated =
        transpile(std::move(lowered_source), source, !no_runtime);
    if (output_mode == OutputMode::CppSource) {
      write_file(output, generated);
      std::cout << "Transpiled " << output.string() << "\n";
      return 0;
    }
    if (!emit_cpp.empty())
      write_file(emit_cpp, generated);

    auto stamp =
        std::chrono::high_resolution_clock::now().time_since_epoch().count();
    fs::path temporary =
        fs::temp_directory_path() /
        ("csp-" + std::to_string(stamp) + (cuda ? ".cu" : ".cpp"));
    write_file(temporary, generated);
    if (compiler.empty())
      compiler = cuda ? "nvcc"
                      : (output_mode == OutputMode::LlvmIr ? "clang++" : "g++");
    std::string command = compiler + " -std=c++20";
    if (output_mode == OutputMode::LlvmIr)
      command += " -S -emit-llvm";
    else if (output_mode == OutputMode::Assembly)
      command += " -S";
    else if (output_mode == OutputMode::Object)
      command += " -c";
    else if (output_mode == OutputMode::SyntaxOnly)
      command += " -fsyntax-only";
    if (!target_triple.empty())
      command += " --target=" + target_triple;
    if (!target_cpu.empty())
      command += " -mcpu=" + target_cpu;
    if (freestanding)
      command += " -ffreestanding -fno-exceptions -fno-rtti";
    if (cuda) {
      command += " -DCSP_CUDA";
      if (!gpu_arch.empty())
        command += " -arch=" + gpu_arch;
    }
    if (native_flags.empty())
      command += " -O2";
    fs::path executable_directory = fs::absolute(argv[0]).parent_path();
    std::vector<fs::path> standard_include_candidates = {
        executable_directory / "include",
        executable_directory.parent_path() / "include"};
    for (const fs::path &standard_include : standard_include_candidates)
      if (fs::exists(standard_include))
        command += " -I" + quote(standard_include);
    for (const auto &flag : native_flags)
      command += " " + flag;
    command += " " + quote(temporary);
    if (output_mode != OutputMode::SyntaxOnly)
      command += " -o " + quote(fs::absolute(output));
    int result = std::system(command.c_str());
    std::error_code ignored;
    fs::remove(temporary, ignored);
    if (result != 0)
      throw std::runtime_error("native compilation failed");

    if (output_mode == OutputMode::SyntaxOnly)
      std::cout << "C+ syntax and semantic checks passed\n";
    else
      std::cout << "Built " << output.string() << "\n";
    if (run && output_mode != OutputMode::Executable)
      throw std::runtime_error("--run requires executable output mode");
    if (hopa) {
      if (output_mode != OutputMode::Executable)
        throw std::runtime_error("hopa requires executable output mode");
      fs::path stage2 =
          output.parent_path() /
          (output.stem().string() + "-stage2" + output.extension().string());
      std::string bootstrap =
          quote(fs::absolute(output)) + " " + quote(fs::absolute(source)) +
          " --no-runtime -I . -O2 -o " + quote(fs::absolute(stage2));
#ifdef _WIN32
      // cmd.exe requires an additional pair around a command whose executable
      // and arguments are both quoted.
      bootstrap = '"' + bootstrap + '"';
#endif
      if (std::system(bootstrap.c_str()) != 0)
        throw std::runtime_error("hopa stage 2 self-compilation failed");
      std::cout << "Hopa bootstrap completed " << stage2.string() << "\n";
    }
    if (run)
      return std::system(quote(fs::absolute(output)).c_str());
    return 0;
  } catch (const csp::CompileError &error) {
    csp::DiagnosticEngine diagnostics;
    diagnostics.error(error.location, error.what());
    diagnostics.print(std::cerr);
    return 1;
  } catch (const std::exception &error) {
    std::cerr << "cspc: error: " << error.what() << "\n";
    return 1;
  }
}
