// Generated by the C+ Rust transpiler.
use std::ffi::{c_char, c_int};
unsafe extern "C" { fn printf(format: *const c_char, ...) -> c_int; }

fn csp_main() -> i32 {
    let mut num: i32 = 2;
    unsafe { printf(b"hello from C+; num = %d\n\0".as_ptr() as *const c_char, num) };
    for i in 0..3 {
        unsafe { printf(b"iteration %d\n\0".as_ptr() as *const c_char, i) };
    }
    return 0;
}

fn main() { std::process::exit(csp_main()); }
