// Generated by C+ 0.2.0

#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <cstddef>
#include <cstring>
#include <string>
#include <vector>
using u8 = std::uint8_t;
using u16 = std::uint16_t;
using u32 = std::uint32_t;
using u64 = std::uint64_t;
using u128 = unsigned __int128;
using unichar = char32_t;
template<class... Args> int printc(const char* format, Args... args) {
    return std::printf(format, args...);
}
inline int printc(const std::string& value) {
    return std::printf("%s", value.c_str());
}

#line 1 "hello.csp"

int main(){
    int num = 2;
    printc("hello from C+; num = %d\n", num);

    for(int i = 0; i < 3; i++){
        printc("iteration %d\n", i);
    }
    return 0;
}

