/* Generated by the C+ C transpiler. */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
typedef uint8_t u8; typedef uint16_t u16; typedef uint32_t u32;
typedef uint64_t u64; typedef __uint128_t u128; typedef uint32_t unichar;
#define printc printf


int main(){
    int num = 2;
    printc("hello from C+; num = %d\n", num);

    for(int i = 0; i < 3; i++){
        printc("iteration %d\n", i);
    }
    return 0;
}

