# CMake generated Testfile for 
# Source directory: C:/Users/DeLL/Desktop/C+
# Build directory: C:/Users/DeLL/Desktop/C+/build-release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("csp.frontend" "C:/Users/DeLL/Desktop/C+/build-release/csp_frontend_tests.exe")
set_tests_properties("csp.frontend" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;62;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.headers" "C:/Users/DeLL/Desktop/C+/build-release/csp_header_smoke.exe")
set_tests_properties("csp.headers" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;66;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.codegen.manifest" "C:/Users/DeLL/Desktop/C+/build-release/csp-codegen.exe" "--validate-only")
set_tests_properties("csp.codegen.manifest" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;68;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.semantic.valid-overloads" "C:/Users/DeLL/Desktop/C+/build-release/cspc.exe" "C:/Users/DeLL/Desktop/C+/tests/semantic/valid_overloads.csp" "--check")
set_tests_properties("csp.semantic.valid-overloads" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;70;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.semantic.valid-bugemoan" "C:/Users/DeLL/Desktop/C+/build-release/cspc.exe" "C:/Users/DeLL/Desktop/C+/tests/semantic/valid_bugemoan.csp" "--check")
set_tests_properties("csp.semantic.valid-bugemoan" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;72;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.semantic.valid-hopa" "C:/Users/DeLL/Desktop/C+/build-release/cspc.exe" "C:/Users/DeLL/Desktop/C+/tests/semantic/valid_hopa.csp" "--check")
set_tests_properties("csp.semantic.valid-hopa" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;74;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.semantic.valid-match" "C:/Users/DeLL/Desktop/C+/build-release/cspc.exe" "C:/Users/DeLL/Desktop/C+/tests/semantic/valid_match.csp" "--check")
set_tests_properties("csp.semantic.valid-match" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;76;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.semantic.reject-non-exhaustive-match" "C:/Users/DeLL/Desktop/C+/build-release/cspc.exe" "C:/Users/DeLL/Desktop/C+/tests/semantic/invalid_non_exhaustive_match.csp" "--check")
set_tests_properties("csp.semantic.reject-non-exhaustive-match" PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;78;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.semantic.valid-ctfe" "C:/Users/DeLL/Desktop/C+/build-release/cspc.exe" "C:/Users/DeLL/Desktop/C+/tests/semantic/valid_ctfe.csp" "--check")
set_tests_properties("csp.semantic.valid-ctfe" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;81;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.semantic.reject-ctfe" "C:/Users/DeLL/Desktop/C+/build-release/cspc.exe" "C:/Users/DeLL/Desktop/C+/tests/semantic/invalid_ctfe.csp" "--check")
set_tests_properties("csp.semantic.reject-ctfe" PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;83;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.features.zero-cost" "C:/Users/DeLL/Desktop/C+/build-release/cspc.exe" "C:/Users/DeLL/Desktop/C+/tests/features/zero_cost.csp" "--check")
set_tests_properties("csp.features.zero-cost" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;86;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.features.safe-defaults" "C:/Users/DeLL/Desktop/C+/build-release/cspc.exe" "C:/Users/DeLL/Desktop/C+/tests/features/safe_defaults.csp" "--check")
set_tests_properties("csp.features.safe-defaults" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;88;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.semantic.reject-optional-dereference" "C:/Users/DeLL/Desktop/C+/build-release/cspc.exe" "C:/Users/DeLL/Desktop/C+/tests/semantic/invalid_optional_dereference.csp" "--check")
set_tests_properties("csp.semantic.reject-optional-dereference" PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;90;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.semantic.reject-immutable-assignment" "C:/Users/DeLL/Desktop/C+/build-release/cspc.exe" "C:/Users/DeLL/Desktop/C+/tests/semantic/invalid_immutable_assignment.csp" "--check")
set_tests_properties("csp.semantic.reject-immutable-assignment" PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;93;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.semantic.reject-cross-function-goto" "C:/Users/DeLL/Desktop/C+/build-release/cspc.exe" "C:/Users/DeLL/Desktop/C+/tests/semantic/invalid_cross_function_goto.csp" "--check")
set_tests_properties("csp.semantic.reject-cross-function-goto" PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;96;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.semantic.reject-duplicate-default" "C:/Users/DeLL/Desktop/C+/build-release/cspc.exe" "C:/Users/DeLL/Desktop/C+/tests/semantic/invalid_duplicate_default.csp" "--check")
set_tests_properties("csp.semantic.reject-duplicate-default" PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;99;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
add_test("csp.semantic.reject-duplicate-case" "C:/Users/DeLL/Desktop/C+/build-release/cspc.exe" "C:/Users/DeLL/Desktop/C+/tests/semantic/invalid_duplicate_case.csp" "--check")
set_tests_properties("csp.semantic.reject-duplicate-case" PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/Users/DeLL/Desktop/C+/CMakeLists.txt;102;add_test;C:/Users/DeLL/Desktop/C+/CMakeLists.txt;0;")
